---

env:
  node: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  no-console: 0

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings
